### ISSUE TITLE
error TS2304: Cannot find name 'FBUIParams'.

### ISSUE THREAD

**Issue by ishehata** [aryeh/ng2-facebook-rxjs#2]
i am using webpack to build angular, and i am getting error

ERROR in /Users/e_/c_*/frontend/node_modules/ng2-facebook-rxjs/dist/facebook.service.d.ts
(20,16): error TS2304: Cannot find name 'FBUIParams'.

**Comment by aryeh** [comment]
it isn't finding the fbsdk typings.

`typings install --global --source=dt --save fbsdk`

**Comment by ishehata** [comment]
thanks, that solved the issue.

**Comment by dsslayers** [comment]
FYI, this did not work for me. I gt it to work by removing that code from the d.ts. file. Everything still seems to work without it.

**Comment by bjornharvold** [comment]
Created a new issue for this: https://github.com/aryeh/ng2-facebook-rxjs/issues/5
