### ISSUE TITLE
EXCEPTION: Error: Uncaught (in promise): ReferenceError: FB is not defined

### ISSUE THREAD

**Issue by Dralac** [aryeh/ng2-facebook-rxjs#3]
I'm trying to make this work with angular-universal and webpack, but even I have included the SDK script in the header I'm getting the error: _EXCEPTION: Error: Uncaught (in promise): ReferenceError: FB is not defined_

Any hints?

**Comment by aryeh** [comment]
Sounds like your angular code is getting run before the Facebook sdk  defines FB.  It needs to be run after FB has been defined.

**Comment by Dralac** [comment]
Thanks @aryeh 

Probably some configuration issues on my side, just wanted to check with you so I can debug in proper direction.
